# Dependency-ordered load

require "./Version"
require "./Tools/**"
require "./Types/**"
require "./Diagnostic/**"
require "./Lexer/**"
require "./Ast/Node"
require "./Ast/**"
require "./Parser/**"
require "./Sema/**"
require "./Codegen/**"
require "./Backend/**"
require "./Driver/**"
require "./CLI/**"
