// AstInvariant.cpp — order 40, Analysis. The guardrail that makes "no debt"
// structural instead of a snapshot.
//
// Everything the earlier phases achieved is a property of the *current* corpus:
// lower every sugar node, type every value. Without a mechanical check, the
// first commit after this one silently gives it back. Two invariants, both
// checked on every build:
//
//   1. **No residual sugar.** No expression in the arena still has a kind
//      marked VOLT_EXPR_SUGAR in Nodes.inl. Membership is a constexpr set
//      generated *by the manifest* — no switch, so a tenth sugar node is one
//      line in Nodes.inl and nothing here changes.
//
//   2. **Typing is total.** Every expression in *value position* has a type.
//      Value position is the set a backend will actually ask for a value at, so
//      a `Member` used as a callee or an `Identifier` naming a type is
//      deliberately not in it.
//
// This pass creates no node, which is what lets it run after TypeChecker
// without violating the structural invariant of PassList.inl.

#include "Volt/Core/Meta/Overloaded.hpp"
#include "Volt/Frontend/AST/AstContext.hpp"
#include "Volt/Frontend/AST/AstQuery.hpp"
#include "Volt/Frontend/AST/Expr.hpp"
#include "Volt/Frontend/AST/Node.hpp"
#include "Volt/Frontend/AST/Stmt.hpp"
#include "Volt/MiddleEnd/Core/Pass.hpp"

#include "LiteralInferencer.hpp"

#include <algorithm>
#include <array>
#include <cstddef>
#include <string>
#include <variant>
#include <vector>

namespace
{

using namespace Volt;

// Generated by the manifest: only the nodes written VOLT_EXPR_SUGAR land here,
// because the default VOLT_EXPR expands to nothing.
constexpr std::array SugarKinds = {
#define VOLT_EXPR_SUGAR( Name ) Frontend::ExprKind::Name,
#include "Volt/Frontend/AST/Nodes.inl"
};

[[nodiscard]] bool IsSugar ( Frontend::ExprKind Kind )
{
    return std::ranges::find( SugarKinds, Kind ) != SugarKinds.end();
}

class InvariantChecker
{

public:

    InvariantChecker ( MiddleEnd::Core::PassContext &InContext, std::vector<bool> InMetadata )
        : Context( InContext ), Metadata( std::move( InMetadata ) )
    {
    }

    void Run ()
    {
        CollectValuePositions();

        const std::size_t Count = Context.Ast.ExprCount();
        for ( std::size_t Index = 0; Index < Count; ++Index )
        {
            const Frontend::ExprId Id{ static_cast<Frontend::ExprId::ValueType>( Index ) };
            CheckSugar( Id );
            CheckTyped( Id );
        }
    }

private:

    void CheckSugar ( Frontend::ExprId Id )
    {
        if ( not IsSugar( KindOf( Context.Ast.Expr( Id ) ) ) )
        {
            return;
        }

        // Written inside a generic definition: a Lowering pass that needs a
        // settled type (LowerClosureLit's own guard is the current example)
        // cannot rewrite it here, only MiddleEnd::TypeSystem::ReinstantiateBody can, once per
        // concrete instantiation (core-ast.md's "Generic definition bodies";
        // CheckTyped grants the identical exemption below for the same
        // reason). The corpus-wide census this check protects still holds:
        // every *reachable* instantiation is lowered, just never the shared,
        // unconcretized template.
        if ( Context.Values.IsDeferred( Id ) )
        {
            return;
        }

        ++Context.Stats.ResidualSugarNodes;
        Report( Id, "residual sugar node '" + std::string{ Frontend::NodeName( Context.Ast.Expr( Id ) ) } +
                        "' survived lowering; a Lowering pass must rewrite it before TypeChecker" );
    }

    void CheckTyped ( Frontend::ExprId Id )
    {
        if ( Id.Value >= ValuePosition.size() or not ValuePosition[Id.Value] )
        {
            return;
        }

        // InferExpr short-circuits anything MetadataExprs marked — annotation
        // arguments and macro bodies are never evaluated, so they legitimately
        // carry no type. Without this exclusion the 44 Annotation nodes in the
        // corpus would each be a false positive.
        if ( Id.Value < Metadata.size() and Metadata[Id.Value] )
        {
            return;
        }

        // Written inside a generic definition, where `T` is not yet a type.
        // Deferred until instantiation, which is monomorphisation, which is
        // codegen — the contract a backend gets is "typed once instantiated",
        // see rules/core-ast.md.
        if ( Context.Values.IsDeferred( Id ) )
        {
            return;
        }
        if ( Context.Values.ExprType( Id ).IsValid() )
        {
            return;
        }

        ++Context.Stats.UntypedValueExprs;
        Report( Id, std::string{ Frontend::NodeName( Context.Ast.Expr( Id ) ) } + " in value position was never given a type" );
    }

    /// Mark every ExprId a backend will ask for a value at. Written as one
    /// visit over each node's own shape rather than a traversal: the arena is
    /// flat, so "who is used as a value" is a local question at each parent.
    void CollectValuePositions ()
    {
        ValuePosition.assign( Context.Ast.ExprCount(), false );

        const std::size_t ExprTotal = Context.Ast.ExprCount();
        for ( std::size_t Index = 0; Index < ExprTotal; ++Index )
        {
            std::visit(
                Meta::Overloaded{
                    [&] ( const Frontend::Binary &Node )
                    {
                        Mark( Node.Lhs );
                        Mark( Node.Rhs );
                    },
                    [&] ( const Frontend::Unary &Node ) { Mark( Node.Operand ); },
                    [&] ( const Frontend::Deref &Node ) { Mark( Node.Operand ); },
                    [&] ( const Frontend::Ternary &Node )
                    {
                        Mark( Node.Cond );
                        Mark( Node.Then );
                        Mark( Node.Else );
                    },
                    [&] ( const Frontend::Assign &Node ) { Mark( Node.Value ); },
                    [&] ( const Frontend::Call &Node )
                    {
                        for ( const Frontend::ExprId Arg : Node.Args )
                        {
                            Mark( Arg );
                        }
                        Mark( Node.BlockArg );
                    },
                    [&] ( const Frontend::ArrayLit &Node )
                    {
                        for ( const Frontend::ExprId Elem : Node.Elements )
                        {
                            Mark( Elem );
                        }
                    },
                    [&] ( const Frontend::HashLit &Node )
                    {
                        for ( const Frontend::ExprId Key : Node.Keys )
                        {
                            Mark( Key );
                        }
                        for ( const Frontend::ExprId Value : Node.Values )
                        {
                            Mark( Value );
                        }
                    },
                    [] ( const auto & ) {},
                },
                Context.Ast.Expr( Frontend::ExprId{ static_cast<Frontend::ExprId::ValueType>( Index ) } ) );
        }

        const std::size_t StmtTotal = Context.Ast.StmtCount();
        for ( std::size_t Index = 0; Index < StmtTotal; ++Index )
        {
            std::visit(
                Meta::Overloaded{
                    [&] ( const Frontend::LocalDecl &Node ) { Mark( Node.Init ); },
                    [&] ( const Frontend::Return &Node ) { Mark( Node.Value ); },
                    [] ( const auto & ) {},
                },
                Context.Ast.Stmt( Frontend::StmtId{ static_cast<Frontend::StmtId::ValueType>( Index ) } ) );
        }
    }

    void Mark ( Frontend::ExprId Id )
    {
        if ( Id.IsValid() and Id.Value < ValuePosition.size() )
        {
            ValuePosition[Id.Value] = true;
        }
    }

    void Report ( Frontend::ExprId Id, std::string Message )
    {
        Context.Diags.Error( Frontend::LocOf( Context.Ast.Expr( Id ) ), std::move( Message ) );
    }

    MiddleEnd::Core::PassContext &Context;
    std::vector<bool> Metadata;
    std::vector<bool> ValuePosition;
};

} // namespace

void Volt::MiddleEnd::Analysis::AstInvariant ( Core::PassContext &Context )
{
    // See TypeChecker.cpp's identical comment: TypeCheckerPass has not moved
    // yet (Etape 8), only this entry point's own namespace had to.
    namespace TypeCheckerPass = Volt::MiddleEnd::Analysis;

    InvariantChecker( Context, Analysis::MetadataExprs( Context.Ast ) ).Run();
}
