if( EXISTS "${DB_IN}" )
  file( READ "${DB_IN}" DB_CONTENT )
  string( REGEX REPLACE " -freflection" "" DB_CONTENT "${DB_CONTENT}" )
  string( REGEX REPLACE " -Winvalid-pch" "" DB_CONTENT "${DB_CONTENT}" )
  string( REGEX REPLACE " -include [^ ]*cmake_pch\\.hxx" "" DB_CONTENT "${DB_CONTENT}" )
  file( WRITE "${DB_OUT}" "${DB_CONTENT}" )
else()
  file( WRITE "${DB_OUT}" "[]" )
endif()
