#pragma once

// InstructionTables.hpp — the manifest of primitive machine operations.
//
// `a + b` on a primitive is an instruction, not a method body: when
// UnitCallees left the operator *unresolved*, the receiver's
// Primitive{ Spelling, Bits } is what selects it (rules/core-ast.md,
// rules/zero-hardcode.md). The compiler reads one character of the spelling to
// place it in a family and nothing else — it never learns that "f64" is any
// particular Volt type.
//
// Three families, derived from the spelling and never from a name:
//
//   SInt   spelling starts with 'i' and is wider than one bit, or is "ptr"
//   UInt   spelling starts with 'u'
//   Float  spelling starts with 'f'
//
// The signed/unsigned split exists exactly where the machine has two
// instructions for one operator (`sdiv`/`udiv`, `icmp slt`/`icmp ult`) and
// nowhere else — `add` is the same instruction either way, so it is written
// once per family rather than made conditional.
//
// This replaces the old `Instructions.inl`, which was the same three tables
// generated by including one file three times under three different macro
// definitions. The rows are now written out directly: there is exactly one
// consumer (this module), the macro indirection bought no second reader, and a
// plain `constexpr` array is what a reader — and a debugger — can actually see.
// Adding an operator is still one line; adding a *family* is still one
// EOpFamily row plus its lines.
//
// Deliberately *not* here, because none of them is a table lookup:
//   - `and` / `or` (and `&&` / `||`) short-circuit, so they are control flow;
//   - `not` / `!` on a one-bit value is `xor true`, which needs the operand's
//     width, so it is EUnaryOp::LogicalNot rather than a BinaryOps row;
//   - pointer `+` / `-` are heterogeneous (`( offset : UInt64 ) -> Pointer<T>`,
//     declared on the pointer nominal itself) and emit a `gep` whose stride is
//     the pointee's size — an address computation, not an arithmetic opcode.

#include "Volt/Frontend/Lexer/Token.hpp"

#include <llvm/IR/InstrTypes.h>
#include <llvm/IR/Instruction.h>

#include <cstdint>
#include <string_view>

namespace Volt
{

namespace Backend
{

    namespace Llvm
    {

        // The family a spelling belongs to. Derived from one character, which is
        // the whole vocabulary rules/zero-hardcode.md grants the C++ side:
        // `"i32"` selects signed instructions because it starts with `i`, not
        // because anything here knows it was written `Int32`.
        enum class EOpFamily : std::uint8_t
        {

            None,
            SInt,
            UInt,
            Float,
        };

        // The unary forms, which are not BinaryOps rows: each needs the
        // operand's own width or type to build its constant.
        enum class EUnaryOp : std::uint8_t
        {

            Neg,        // 0 - x
            FNeg,       // fneg x
            BitNot,     // x xor -1
            LogicalNot, // x xor true — the i1 case
        };

        struct BinOpRow
        {

            EOpFamily Family = EOpFamily::None;
            Frontend::TokenKind Op{};
            llvm::Instruction::BinaryOps Opcode{};
        };

        struct CmpRow
        {

            EOpFamily Family = EOpFamily::None;
            Frontend::TokenKind Op{};
            llvm::CmpInst::Predicate Predicate{};
        };

        struct UnOpRow
        {

            EOpFamily Family = EOpFamily::None;
            Frontend::TokenKind Op{};
            EUnaryOp Kind{};
        };

        // The family of an opaque spelling. `"ptr"` joins the unsigned
        // integers: an address has no sign bit, so `p < q` is `icmp ult` — and
        // pointer `+`/`-` never reach a table row at all, being address
        // arithmetic.
        [[nodiscard]] EOpFamily FamilyOf ( std::string_view Spelling );

        // Null when the family carries no such operator, which is what the
        // caller reports.
        [[nodiscard]] const BinOpRow *FindBinOp ( EOpFamily Family, Frontend::TokenKind Op );
        [[nodiscard]] const CmpRow *FindCmp ( EOpFamily Family, Frontend::TokenKind Op );
        [[nodiscard]] const UnOpRow *FindUnOp ( EOpFamily Family, Frontend::TokenKind Op );

    } // namespace Llvm

} // namespace Backend

} // namespace Volt
